#!/bin/sh
# =============================================================
# Script to control prefered apps to launch for all themes
# Author:  z0mbi3
# Repo:    https://github.com/gh0stzk/dotfiles
# Date:    24.04.2025
# Copyright (C) 2021-2025 gh0stzk <z0mbi3.zk@protonmail.com>
# Licensed under GPL-3.0 license
# =============================================================

# WIDGET_DIR="$HOME/.config/bspwm/eww"

case "$1" in
	--menu)
		/home/main/.local/share/rawr/RofiLauncher --launcher
		;;
	--rice)
		RiceSelector
		;;
	--terminal)
		kitty
		;;
	--floating)
		Term --floating
		;;
	--update)
		Term --update
		;;
	--checkupdates)
		Term --checkupdates
		;;
	--netmanager)
		/home/main/.local/share/rawr/NetManagerDM
		;;
	--bluetooth)
		rofi-bluetooth
		;;
	--clipboard)
		clipcat-menu
		;;
	--screenshot)
		ScreenShoTer
		;;
	--powermenu)
		/home/main/.local/share/rawr/PowerMenu
		;;
	--android)
		AndroidMount
		;;
	--keyboard)
		KeyBoardL
		;;
	--yazi)
		Term --yazi
		;;
	--nvim)
		Term --nvim
		;;
	--music)
		Term --music
		;;
	--fetch)
		Term --fetch
		;;
	--scratch)
		Bspwm-ScratchPad
		;;
		# Apps
	--filemanager)
		thunar
		;;
	--browser)
		firefox
		;;
	--editor)
		geany
		;;
	--telegram)
		telegram-desktop
		;;
	--whats)
		firefox -new-tab https://web.whatsapp.com/
		;;
	--soundcontrol)
		pavucontrol
		;;
		*)
		echo "Invalid Option"
		;;
esac
